carros/urls.py
#!/usr/local/bin/python
# coding: utf-8

from django.conf.urls import url
from . import views


urlpatterns = [
    # url(r'^$', views.listar_carros, name="listar_carros"),
    url(r'^$', views.CarroList.as_view(), name="listar_carros"),
    url(r'^marcas/$', views.listar_marcas, name="listar_marcas"),
    # url(r'^marcas/agregar/$', views.agregar_marca, name="agregar_marca"),
    url(r'^marcas/agregar/$', views.MarcaCreate.as_view(), name="agregar_marca"),
]

paulwalker/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from paulwalker import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.home, name="home"),
    url(r'^carros/', include('carros.urls')),
]

carros/models.py
from django.db import models


class Marca(models.Model):
    nombre = models.CharField(
        max_length=255, unique=True,
    )

    def __unicode__(self):
        return self.nombre


class Carro(models.Model):
    nombre = models.CharField(
        max_length=255
    )
    marca = models.ForeignKey(
        Marca
    )

    def __unicode__(self):
        return self.nombre

carros/forms.py
from django import forms
from carros.models import Marca


class AgregarMarcaForm(forms.ModelForm):
    class Meta:
        model = Marca
        fields = ["nombre"]

carros/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Marca, Carro
from .forms import AgregarMarcaForm
from django.views.generic import ListView, CreateView
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages


class CarroList(ListView):
    model = Carro
    context_object_name = 'carros'


def listar_carros(request):
    carros = Carro.objects.all()
    data = {
        'carros': carros,
    }
    return render(request, "carros.html", data)


def listar_marcas(request):
    marcas = Marca.objects.all()
    data = {
        'marcas': marcas,
    }
    return render(request, "marcas.html", data)


class MarcaCreate(CreateView):
    model = Marca
    template_name = 'agregar_marca.html'
    success_url = reverse_lazy('listar_marcas')
    fields = ['nombre']

    def get_success_url(self):
        messages.success(self.request, 'Marca agregada exitosamente!')
        return super(MarcaCreate, self).get_success_url()


def agregar_marca(request):
    if request.method == "POST":
        form = AgregarMarcaForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse("Marca Agregada")
    else:
        form = AgregarMarcaForm()
    data = {
        'form': form
    }
    return render(request, "agregar_marca.html", data)

paulwalker/views.py
from django.shortcuts import render


def home(request):
    return render(request, "index.html")

carros/templates/carros/carro_list.html
{% extends "base.html" %}

{% block titulo %}:: Lista de carros{% endblock %}

{% block content %}
	{% load staticfiles %}
	<section id="portfolio_single">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="portfolio-header text-center">
                        <h2>Lista de carros</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="related">
	    <div class="container">
	        <div class="row">
	             <div class="related text-center">
	              {% for c in carros %}
		    
	                <div class="col-md-3 col-sm-6">
	                    <div class="rel-post">
	                        <a href="#">
	                            <img src="{% static 'carros/images/blog/pic6.jpg' %}" alt="" class="img-responsive">
	                            <div class="caption">
	                                <h4>{{ c.nombre }}</h4>
	                                <p>{{ c.marca }}</p>
	                            </div>
	                        </a>
	                    </div>
	                </div>
	                {% endfor %}
	            </div>
	        </div>
	    </div>
	</section>

{% endblock %}

paulwalker/templates/agregar_marca.html
{% extends "base.html" %}

{% block titulo %}:: Lista de marcas{% endblock %}

{% block content %}

    <style>
    div.red{
        color: red;
    }
    </style>
    <section id="portfolio_single">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="portfolio-header text-center">
                        <h2>Agregar Nueva Marca</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>


<section id="related">
    <div class="container">
        <div class="row">
            <div class="col-md-12 center">
                <div class="">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-level">
                            <label for="id_nombre">Nombre de la marca:</label>
                        </div>
                        <div class="form-level">
                            {{ form.nombre }}
                            <span class="form-icon fa fa-car"></span>
                        </div>
                        <div class="col-md-12 text-center">
                            <button type="submit" class="btn btn-main featured">Guardar Marca</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>    
{% endblock %}

paulwalker/templates/base.html
 <!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
    <!-- Basic Page Needs
    ================================================== -->
        <meta charset="utf-8">
        <title>PaulWalker {% block titulo %}{% endblock %}</title>
        <meta name="description" content="">
        <!-- Mobile Specific Metas
    ================================================== -->
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
         <!-- CSS
         ================================================== -->
        {% load staticfiles %}
        <link rel="shortcut icon" href="{% static 'carros/images/favicon.ico' %}" type="image/x-icon">
<link rel="icon" href="{% static 'carros/images/favicon.ico' %}" type="image/x-icon">
        <!-- Bootstrap -->
        <link rel="stylesheet" href="{% static 'carros/css/bootstrap.min.css' %}"/>
        <!-- FontAwesome -->
        <link rel="stylesheet" href="{% static 'carros/css/font-awesome.min.css' %}"/>
        <!-- Animation -->
        <link rel="stylesheet" href="{% static 'carros/css/animate.css' %}" />
        <!-- Owl Carousel -->
        <link rel="stylesheet" href="{% static 'carros/css/owl.carousel.css' %}"/>
        <link rel="stylesheet" href="{% static 'carros/css/owl.theme.css' %}"/>
        <!-- Pretty Photo -->
        <link rel="stylesheet" href="{% static 'carros/css/prettyPhoto.css' %}"/>
        <!-- Main color style -->
        <link rel="stylesheet" href="{% static 'carros/css/red.css' %}"/>
        <!-- Template styles-->
        <link rel="stylesheet" href="{% static 'carros/css/custom.css' %}" />
        <!-- Responsive -->
        <link rel="stylesheet" href="{% static 'carros/css/responsive.css' %}" />
        <link rel="stylesheet" href="{% static 'carros/css/jquery.fancybox.css' %}" type="text/css" media="screen" />
	
		<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
        <link href='http://fonts.googleapis.com/css?family=Lato:400,300' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500' rel='stylesheet' type='text/css'>
    </head>

 <body data-spy="scroll" data-target=".navbar-fixed-top">
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

    <header id="section_header" class="navbar-fixed-top main-nav" role="banner">
    	<div class="container">
    		<!-- <div class="row"> -->
                 <div class="navbar-header ">
                     <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="{% url 'home' %}">
                            <img src="{% static 'carros/images/logo-pw.jpg' %}" alt="">
                        </a>
                 </div><!--Navbar header End-->
                 	<nav class="collapse navbar-collapse navigation" id="bs-example-navbar-collapse-1" role="navigation">
                        <ul class="nav navbar-nav navbar-right ">
                           	<li class="active"> <a href="#slider_part" >Inicio </a></li>
                            <li><a href="#service"  >Secciones</a> </li>
                            <li><a href="#team" >Equipo </a> </li>
                            <!-- <li><a href="#blog" >Blog</a> </li> -->
                            <li><a href="#contact" >Contáctanos</a> </li>
                        </ul>
                     </nav>
                </div><!-- /.container-fluid -->
</header>
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade in" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <p>{{ message }}</p>
    </div>
  {% endfor %}
{% endif %}
{% block content %}

{% endblock content %}
<section id="footer">
    <div class="footer_top">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <h3 class="menu_head">Menu</h3>
                    <div class="footer_menu">
                        <ul>
                            <li><a href="##slider_part">Inicio</a></li>
                            <li><a href="#service">Secciones</a></li>
                            <li><a href="#team">Equipo</a></li>
                            <li><a href="#contact">Contáctanos</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <h3 class="menu_head">Contáctanos</h3>
                    <div class="footer_menu_contact">
                        <ul>
                            <li> <i class="fa fa-home"></i>
                                <span> Cra. 53 # 76 - 239 Of. 405 C.C. Habitat</span></li>
                            <li><i class="fa fa-map-marker"></i>
                            <span> www.meetup.com/es/Django-Barranquilla</span></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="footer_b">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="footer_bottom">
                        <p class="text-block"> &copy; Realizado por Django Barranquilla </span></p>
                    </div>
                </div>
                <div class="col-md-6 col-sm-6 col-xs-12">
                    <div class="footer_mid pull-right">
                        <ul class="social-contact list-inline">
                            <li> <a href="https://www.facebook.com/groups/813920708682845/"><i class="fa fa-facebook"></i></a></li>
                            <li> <a href="https://twitter.com/djangoquilla"><i class="fa fa-twitter"></i></a></li>
                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
<!-- Footer Area End -->

<!-- Back To Top Button -->
    <div id="back-top">
        <a href="#slider_part" class="scroll" data-scroll>
            <button class="btn btn-primary" title="Volver al Inicio"><i class="fa fa-angle-up"></i></button>
        </a>
    </div>
    <!-- End Back To Top Button -->



<!-- Javascript Files
    ================================================== -->
    <!-- initialize jQuery Library -->

		<!-- initialize jQuery Library -->
        <!-- Main jquery -->
		    <script type="text/javascript" src="{% static 'carros/js/jquery.js' %}"></script>
        <!-- Bootstrap jQuery -->
        <script src="{% static 'carros/js/bootstrap.min.js' %}"></script>
        <!-- Owl Carousel -->
        <script src="{% static 'carros/js/owl.carousel.min.js' %}"></script>
        <!-- Isotope -->
        <script src="{% static 'carros/js/jquery.isotope.js' %}"></script>
        <!-- Pretty Photo -->
		    <script type="text/javascript" src="{% static 'carros/js/jquery.prettyPhoto.js' %}"></script>
        <!-- SmoothScroll -->
        <script type="text/javascript" src="{% static 'carros/js/smooth-scroll.js' %}"></script>
        <!-- Image Fancybox -->
        <script type="text/javascript" src="{% static 'carros/js/jquery.fancybox.pack.js' %}"></script>
        <!-- Counter  -->
        <script type="text/javascript" src="{% static 'carros/js/jquery.counterup.min.js' %}"></script>
        <!-- waypoints -->
        <script type="text/javascript" src="{% static 'carros/js/waypoints.min.js' %}"></script>
        <!-- Bx slider -->
        <script type="text/javascript" src="{% static 'carros/js/jquery.bxslider.min.js' %}"></script>
        <!-- Scroll to top -->
        <script type="text/javascript" src="{% static 'carros/js/jquery.scrollTo.js' %}"></script>
        <!-- Easing js -->
        <script type="text/javascript" src="{% static 'carros/js/jquery.easing.1.3.js' %}"></script>
   		 <!-- PrettyPhoto -->
        <script src="{% static 'carros/js/jquery.singlePageNav.js' %}"></script>
      	<!-- Wow Animation -->
        <script src="{% static 'carros/js/wow.min.js' %}" type="js/javascript" ></script>
        <!-- Google Map  Source -->
        <script src="{% static 'carros/js/gmaps.js' %}" type="text/javascript" ></script>
			 <!-- Custom js -->
        <script src="{% static 'carros/js/custom.js' %}"></script>
	     <script>
		// Google Map - with support of gmaps.js
     var map;
        map = new GMaps({
          div: '#map',
          lat: 11.0038933,
          lng: -74.8070893,
          scrollwheel: false,
          panControl: false,
          zoomControl: false,
        });

        map.addMarker({
          lat: 11.0038933,
          lng: -74.8070893,
          title: 'Barranquilla',
          infoWindow: { 
            content: '<p> Barranquilla, Colombia</p>'
          },
          icon: "static/carros/images/map1.png"
        });
      	</script>
 
    </body>
</html>

paulwalker/templates/marcas.html
{% extends "base.html" %}

{% block titulo %}:: Lista de marcas{% endblock %}

{% block content %}
    {% load staticfiles %}
	<section id="portfolio_single">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="portfolio-header text-center">
                        <h2>Lista de marcas</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section id="related">
	    <div class="container">
	        <div class="row">
	             <div class="related text-center">
	              {% for m in marcas %}
		    
	                <div class="col-md-3 col-sm-6">
	                    <div class="rel-post">
	                        <a href="#">
	                            <img src="{% static 'carros/images/blog/pic12.jpg' %}" alt="" class="img-responsive">
	                            <div class="caption">
	                                <h4>{{ m.nombre }}</h4>
	                            </div>
	                        </a>
	                    </div>
	                </div>
	                {% endfor %}
	            </div>
	        </div>
	    </div>
	</section>
    <section id="port-content">
    <div class="container">
        <div class="row">
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="sidebar">
                        <div class="portfolio-desc">
                            <h4>Agregar Marcas</h4>
                            <p>Agrega más marcas para los vehiculos de Paul Walker.
                            </p>
                        <p><a href="{% url 'agregar_marca' %}" class="btn btn-main featured">Agregar Marca</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}